version: '3'
services:
  postgres:
    image:  postgres:16.2
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: "sadko"
      POSTGRES_USER: "indexer"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - sadko
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - sadko

networks:
  sadko:
    driver: bridge